import type { Metadata, Viewport } from "next";
import "./globals.css";
import { ToastProvider } from "@/components/ui/Toast";
import { ServiceWorker } from "@/components/ServiceWorker";

const APP_URL = process.env.APP_URL ?? "https://smashhero.app";
const DESCRIPTION =
  "Run badminton tournaments and casual matches: players, teams, brackets, live scoring and a global leaderboard.";

export const metadata: Metadata = {
  metadataBase: new URL(APP_URL),
  title: { default: "Smash — Badminton Tournaments & Matches", template: "%s · Smash" },
  description: DESCRIPTION,
  applicationName: "Smash",
  appleWebApp: { capable: true, title: "Smash", statusBarStyle: "black-translucent" },
  openGraph: {
    title: "Smash — Badminton Tournaments & Matches",
    description: DESCRIPTION,
    url: APP_URL,
    siteName: "Smash",
    type: "website",
  },
  twitter: { card: "summary", title: "Smash", description: DESCRIPTION },
};

// Explicit viewport; note we do NOT set maximumScale so pinch-zoom stays on.
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#059669" },
    { media: "(prefers-color-scheme: dark)", color: "#0b1120" },
  ],
};

// iOS home-screen launch splashes (per device) so an installed PWA opens on a
// branded splash instead of a white screen — the iOS parallel to the Android
// TWA splash. Generated by `scripts/gen-ios-splash.mjs` into public/splash/.
const IOS_SPLASH: { cssW: number; cssH: number; dpr: number; file: string }[] = [
  { cssW: 375, cssH: 667, dpr: 2, file: "apple-splash-750-1334.png" },
  { cssW: 414, cssH: 896, dpr: 2, file: "apple-splash-828-1792.png" },
  { cssW: 375, cssH: 812, dpr: 3, file: "apple-splash-1125-2436.png" },
  { cssW: 390, cssH: 844, dpr: 3, file: "apple-splash-1170-2532.png" },
  { cssW: 393, cssH: 852, dpr: 3, file: "apple-splash-1179-2556.png" },
  { cssW: 414, cssH: 736, dpr: 3, file: "apple-splash-1242-2208.png" },
  { cssW: 414, cssH: 896, dpr: 3, file: "apple-splash-1242-2688.png" },
  { cssW: 428, cssH: 926, dpr: 3, file: "apple-splash-1284-2778.png" },
  { cssW: 430, cssH: 932, dpr: 3, file: "apple-splash-1290-2796.png" },
];

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full antialiased">
      <head>
        {IOS_SPLASH.map((s) => (
          <link
            key={s.file}
            rel="apple-touch-startup-image"
            media={`(device-width: ${s.cssW}px) and (device-height: ${s.cssH}px) and (-webkit-device-pixel-ratio: ${s.dpr}) and (orientation: portrait)`}
            href={`/splash/${s.file}`}
          />
        ))}
      </head>
      <body className="min-h-full flex flex-col">
        <ServiceWorker />
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
